import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from '@components/Footer';
import Header from '@components/Header';
import type { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Animal Crossing API by Geraldine',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Suspense>
      <ClerkProvider>
        <html lang="en">
          <body>
            <Header />
            <div className="w-full min-h-screen">{children}</div>
            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </Suspense>
  );
}
