import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from '@components/Footer';
import AdminHeader from '@components/admin/AdminHeader';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Animal Crossing API by Geraldine',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <AdminHeader />
          <div className="w-full min-h-screen">{children}</div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
